FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

WORKDIR /home

COPY /admin-1.0.0-SNAPSHOT-runner /home/ulake-service-admin-runner

RUN chmod +x /home/ulake-service-admin-runner

ENTRYPOINT ["/home/ulake-service-admin-runner"]
