FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

WORKDIR /home

COPY /dashboard-1.0.0-runner /home/ulake-service-dashboard-runner

RUN chmod +x /home/ulake-service-dashboard-runner

ENTRYPOINT ["/home/ulake-service-dashboard-runner"]
