FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

WORKDIR /home

COPY /folder-1.0.0-SNAPSHOT-runner /home/ulake-service-folder-runner

RUN chmod +x /home/ulake-service-folder-runner

ENTRYPOINT ["/home/ulake-service-folder-runner"]
